plot(x = subset(my_data3, Flux =="I")$temps, y = subset(my_data3, Flux =="I")$Ind_Global, axes = F, type = "b", ann=F, col = "red", frame.plot = F)
par(new=TRUE)
plot(x = subset(my_data3, Flux =="ET")$temps, y = subset(my_data3, Flux =="ET")$Ind_Global, axes = F, type = "b", ann=F, col = "blue")
axis(side = 1,at = c(0,50, 100, 150))
par(tcl = -0.5)
axis(1, at=seq(1, 445, by=12), labels=F, lwd=1, lwd.ticks=1)
par(tcl= -0.5)
axis(1, at=seq(1 + 12*2, 450, by=60), lwd=0, lwd.ticks=2)
par(tcl= -0.5)
axis(2)
abline(v=(12*(seq(2,32,by=5)))+1, col="lightgray", lty="dotted")
abline(h=(seq(0,150,25)), col="lightgray", lty="dotted")
title(main="Indice des prix à l'Importation et à l'Exportation", sub="Année 2015 base 100", ylab="Indice global (%)")
axis(1, subset(my_data3, Flux =="ET")$temps, format(subset(my_data3, Flux =="ET")$temps, "%m %Y"), cex.axis = .7)
legend(min(subset(my_data3, Flux =="ET")$temps), max(subset(my_data3, Flux =="ET")$Ind_Global), legend=c("Indice Import", "Indice Export"), col=c("red", "blue"), lty=1:2, lwd = c(2.5, 2.5), cex=0.8)
